//! Symbol resolution for C and C++, without a compiler.
//!
//! Every precise option for this family — `scip-clang`, clangd's index,
//! libclang — hard-requires a `compile_commands.json`, and that file is the
//! problem. It cannot be derived from sources; it is a by-product of running
//! the build. Surveying twelve of the most prominent C and C++ repositories
//! found it checked in **none** of them, and both redis and the Linux kernel
//! gitignore it outright. A resolver built on it would report `unavailable` on
//! very nearly every folder a user points callix at, which is a worse failure
//! than Go's or Rust's "use the toolchain a project of that language already
//! has": there, the requirement is something the project necessarily owns.
//!
//! So the shipped default is this — a symbol table over the sources callix
//! already parsed, reporting [`ResolverStatus::Degraded`]. It is not a
//! placeholder. On a codebase with headers and definitions in the same tree it
//! answers the great majority of call and reference sites, because C and C++
//! resolve names by declaration visibility and that is exactly what a header
//! graph encodes.
//!
//! What it deliberately does not do:
//!
//! - **Evaluate the preprocessor.** Every arm of an `#if` is in the graph, so
//!   two mutually exclusive definitions of one function both exist. A
//!   compiler-based indexer sees one. Which is right depends on why you are
//!   asking; this way nothing is invisible because of a flag nobody recorded.
//! - **Expand macros.** A declaration generated by a macro is not there at all.
//!   This is the family's real blind spot and no amount of CST work fixes it.
//! - **Overload resolution.** A C++ call site names a function; picking which
//!   overload it selects needs the argument types, which needs a type checker.
//!   The call binds to the single candidate when there is one and to the first
//!   in declaration order when there are several, and says so in the edge.
//!
//! A compiler-backed backend plugs in through the adapters' `resolver=`
//! argument, and `src/rustlang/scip.rs` already holds a decoder that does not
//! care which indexer produced the index. Note the asymmetry: a custom resolver
//! is asked "what is defined at this position?", the way every other adapter
//! asks its backend, while the table below answers by name — a compdb-derived
//! index has positions, and this one cannot. Selection stays explicit rather
//! than detected, so that the same folder cannot yield structurally different
//! graphs depending on whether `cmake` happened to have run.

use std::collections::{HashMap, HashSet};

use pyo3::prelude::*;
use pyo3_stub_gen::derive::{gen_stub_pyclass, gen_stub_pymethods};

use crate::node::NodeKind;
use crate::status::ResolverStatus;

/// The built-in backend, as the adapter's `ResolverSlot` records it.
///
/// A marker with no state, because unlike the other four backends this one
/// cannot exist before analysis: [`CFamilyIndex`] is keyed by name and assembled
/// from the declarations and includes the survey pass found, none of which exist
/// until the files have been read. The slot records only *that* the table is in
/// use, and `analyze` builds it.
///
/// It deliberately does not implement `NativeResolver`: that trait's
/// `resolve(path, line, col)` asks "what is defined at this position?", which is
/// the question this family answers in the other direction. A custom resolver
/// passed to `CAdapter` or `CppAdapter` *is* asked that question, because a
/// caller who has a compiler-backed index has positions to answer with.
pub struct SymbolTable;

/// One name a translation unit can see.
#[derive(Clone)]
struct Symbol {
    qualified_name: String,
    kind: NodeKind,
    /// Project-relative file the node was built from.
    file_rel: String,
    /// A file-local symbol is visible only inside `file_rel`; an external one is
    /// visible wherever it has been declared.
    internal: bool,
}

/// Definitions callix parsed, indexed by the shapes a use-site can ask for.
///
/// Not a `#[pyclass]` with `prepare`/`resolve_all`: the C family resolves from
/// the graph the adapter has just built rather than from an external index, so
/// there is nothing to prepare and no subprocess to drive. The adapter calls
/// [`CFamilyIndex::lookup`] directly. [`CFamilyResolver`] below is the
/// Python-visible face, kept so the family reports status and metrics the same
/// way the other four do.
#[derive(Default)]
pub struct CFamilyIndex {
    /// Bare name → every symbol with that name.
    by_name: HashMap<String, Vec<Symbol>>,
    /// Which headers a file can see, transitively through `#include`.
    visible: HashMap<String, HashSet<String>>,
}

impl CFamilyIndex {
    pub fn new() -> Self {
        Self::default()
    }

    /// Records a definition the graph holds.
    ///
    /// `qualified_name` is what the visitor built, so for C++ a callable's
    /// entry already carries its normalized parameter list; the bare name is
    /// what a call site can be matched on, and is indexed separately.
    pub fn declare(
        &mut self,
        bare_name: &str,
        qualified_name: &str,
        kind: NodeKind,
        file_rel: &str,
        internal: bool,
    ) {
        if bare_name.is_empty() {
            return;
        }
        self.by_name.entry(bare_name.to_string()).or_default().push(Symbol {
            qualified_name: qualified_name.to_string(),
            kind,
            file_rel: file_rel.to_string(),
            internal,
        });
    }

    /// Records that `file_rel` includes `included`, directly.
    pub fn include(&mut self, file_rel: &str, included: &str) {
        self.visible
            .entry(file_rel.to_string())
            .or_default()
            .insert(included.to_string());
    }

    /// Closes the include relation transitively.
    ///
    /// A header that includes another makes the second's declarations visible
    /// to everything that includes the first, which is what makes a two-hop
    /// include chain resolve. Iterating to a fixed point rather than recursing
    /// keeps a cyclic include — legal, and common before `#pragma once` was
    /// universal — from being a stack overflow.
    pub fn close_includes(&mut self) {
        loop {
            let mut grew = false;
            let files: Vec<String> = self.visible.keys().cloned().collect();
            for file in files {
                let direct: Vec<String> =
                    self.visible.get(&file).map(|s| s.iter().cloned().collect()).unwrap_or_default();
                let mut additions: Vec<String> = Vec::new();
                for header in &direct {
                    if let Some(inner) = self.visible.get(header) {
                        for deeper in inner {
                            if deeper != &file && !direct.contains(deeper) {
                                additions.push(deeper.clone());
                            }
                        }
                    }
                }
                if additions.is_empty() {
                    continue;
                }
                let entry = self.visible.entry(file).or_default();
                for addition in additions {
                    grew |= entry.insert(addition);
                }
            }
            if !grew {
                return;
            }
        }
    }

    /// Whether a symbol declared in `owner` is visible from `from`.
    fn reachable(&self, from: &str, owner: &str) -> bool {
        from == owner
            || self.visible.get(from).is_some_and(|headers| headers.contains(owner))
    }

    /// The definition a use-site names, if exactly one is a credible answer.
    ///
    /// Returns the qualified name, the kind, and whether the answer was
    /// ambiguous — several visible candidates, which is where overload
    /// resolution would be needed and is not available.
    pub fn lookup(&self, name: &str, from_file: &str) -> Option<(String, NodeKind, bool)> {
        let candidates = self.by_name.get(name)?;

        // A file-local symbol wins inside its own file even when an
        // external-linkage symbol of the same name exists elsewhere: that is
        // what `static` means, and getting it backwards would bind a call to
        // the wrong function in exactly the codebases that use the idiom most.
        let local: Vec<&Symbol> = candidates
            .iter()
            .filter(|s| s.internal && s.file_rel == from_file)
            .collect();
        let visible: Vec<&Symbol> = if local.is_empty() {
            candidates
                .iter()
                .filter(|s| !s.internal && self.reachable(from_file, &s.file_rel))
                .collect()
        } else {
            local
        };

        // Nothing reachable was declared. Falling back to an unreachable
        // candidate would be guessing: `#include` visibility is the language's
        // own rule for which name a translation unit means.
        let chosen = visible.first()?;
        Some((chosen.qualified_name.clone(), chosen.kind, visible.len() > 1))
    }

}

/// The Python-visible resolver for C and C++.
///
/// Exposed for symmetry with the other four adapters and so a caller can ask
/// what it is: `status()` answers `DEGRADED`, always, because a symbol table is
/// not a type checker and reporting `OK` would misrepresent the graph. The
/// resolution itself happens inside `analyze`, against the index built from the
/// sources it has already parsed, so there is no `prepare` step to drive from
/// Python and nothing to configure.
#[gen_stub_pyclass]
#[pyclass(module = "callix._core")]
pub struct CFamilyResolver;

#[gen_stub_pymethods]
#[pymethods]
impl CFamilyResolver {
    #[new]
    fn new() -> Self {
        Self
    }

    /// Always `DEGRADED`: a symbol table over the analysed sources, with no
    /// preprocessor evaluation, no macro expansion and no overload resolution.
    fn status(&self) -> ResolverStatus {
        ResolverStatus::Degraded
    }

    fn __repr__(&self) -> String {
        "CFamilyResolver(status=degraded)".to_string()
    }
}
