# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
import os
import pathlib
import typing
__all__ = [
    "AdapterError",
    "BoundaryRef",
    "CallixError",
    "DuplicateNodeError",
    "EmbeddedTyResolver",
    "GoAdapter",
    "GoResolver",
    "Graph",
    "GraphDiff",
    "ImportClassifier",
    "Node",
    "NodeKind",
    "OccurrenceRef",
    "ParseError",
    "PythonAdapter",
    "Relation",
    "RelationKind",
    "ResolvedRef",
    "ResolverMetrics",
    "ResolverStatus",
    "ResolverTimeout",
    "RustAdapter",
    "RustResolver",
    "SerializationError",
    "Span",
    "SpanIndex",
    "TsImportClassifier",
    "TsResolver",
    "TypeScriptAdapter",
    "apply_boundaries",
    "apply_resolutions",
    "build_root_structure",
    "classify_go_import",
    "classify_rust_import",
    "collect_python_files",
    "collect_typescript_files_py",
    "detect_project_name",
    "diff_graphs",
    "ensure_schema_version",
    "extract_go_boundaries",
    "extract_python_boundaries",
    "extract_rust_boundaries",
    "extract_typescript_boundaries",
    "file_to_qualified_name",
    "filter_nested_files",
    "find_go_roots",
    "find_python_roots",
    "find_rust_roots",
    "find_source_roots",
    "find_typescript_roots",
    "get_stdlib_names",
    "go_detect_project_name",
    "go_parse_dependencies",
    "go_read_module_path",
    "is_go_project",
    "is_package_init",
    "is_python_project",
    "is_rust_project",
    "is_typescript_project",
    "make_boundary_id",
    "make_node_id",
    "node_from_dict",
    "node_to_dict",
    "normalize_http_path",
    "normalize_pkg_name",
    "parse_dependencies",
    "relation_from_dict",
    "relation_to_dict",
    "resolve_relative_import",
    "rust_detect_project_name",
    "rust_parse_dependencies",
    "rust_read_crate_name",
    "ts_build_root_structure",
    "ts_detect_project_name",
    "ts_file_to_qualified_name",
    "ts_find_source_roots",
    "ts_get_stdlib_names",
    "ts_load_path_aliases",
    "ts_parse_dependencies",
    "ts_resolve_relative_import",
    "visit_python_file",
    "visit_typescript_file",
]

class AdapterError(CallixError):
    r"""
    Ошибка на этапе работы адаптера.
    """
    ...

@typing.final
class BoundaryRef:
    r"""
    Один *порт* на межъязыковой границе, найденный в исходнике.
    
    Граница — это контракт между сервисами, который не разрешает ни один
    компилятор: HTTP-маршрут, gRPC-метод, топик очереди, активность
    Temporal. Каждая сторона контракта (сервер — `exposes`, клиент —
    `consumes`) и есть порт.
    
    Координаты 1-based и указывают на место порта (декоратор маршрута,
    вызов `fetch`, вызов `publish`), чтобы адаптер смог сопоставить его с
    объемлющим объявлением.
    """
    @property
    def mechanism(self) -> builtins.str:
        r"""
        Семейство границы: `http` | `grpc` | `queue` | `temporal`.
        """
    @property
    def role(self) -> builtins.str:
        r"""
        `server` (предоставляет контракт) или `client` (потребляет).
        """
    @property
    def key(self) -> builtins.str:
        r"""
        Нормализованный ключ сопоставления, например `GET /users/{}`.
        """
    @property
    def line(self) -> builtins.int: ...
    @property
    def col(self) -> builtins.int: ...
    @property
    def confidence(self) -> builtins.float:
        r"""
        Уверенность экстрактора: 1.0 — литерал, меньше — вывод по контексту.
        """
    @property
    def detail(self) -> builtins.dict[builtins.str, builtins.str]:
        r"""
        Человекочитаемый контекст: метод, путь, топик, фреймворк.
        """
    def __new__(cls, mechanism: builtins.str, role: builtins.str, key: builtins.str, line: builtins.int, col: builtins.int, confidence: builtins.float = ..., detail: typing.Optional[typing.Mapping[builtins.str, builtins.str]] = None) -> BoundaryRef: ...
    def __repr__(self) -> builtins.str: ...

class CallixError(builtins.Exception):
    r"""
    Базовая ошибка callix.
    """
    ...

class DuplicateNodeError(CallixError):
    r"""
    Узел с таким ID уже есть в графе.
    """
    ...

@typing.final
class EmbeddedTyResolver:
    def __new__(cls, base_prefix: builtins.str) -> EmbeddedTyResolver: ...
    def prepare(self, project_root: builtins.str, files: typing.Optional[typing.Sequence[builtins.str]] = None) -> None:
        r"""
        Поднимает базу ty для проекта. `files` не используется: ty сам
        обходит проект по своей конфигурации — в отличие от LSP-версии,
        которой файлы приходилось открывать по одному.
        """
    def resolve_all(self, queries: typing.Sequence[tuple[builtins.str, builtins.int, builtins.int]]) -> builtins.list[typing.Optional[ResolvedRef]]:
        r"""
        Батч позиций → определения, порядок сохраняется.
        """
    def definition_at(self, file: builtins.str, line: builtins.int, col: builtins.int) -> typing.Optional[ResolvedRef]:
        r"""
        Одна позиция → определение.
        """
    def status(self) -> ResolverStatus: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class GoAdapter:
    r"""
    Языковой адаптер для Go-проектов.
    """
    def __new__(cls, *, resolve: builtins.bool = ...) -> GoAdapter:
        r"""
        Args:
        resolve: False отключает резолв-фазу — граф останется
            структурным, а `resolver_status` станет `unavailable`.
        """
    def language(self) -> builtins.str: ...
    def file_extensions(self) -> builtins.set[builtins.str]: ...
    def can_handle(self, project_root: builtins.str | os.PathLike | pathlib.Path) -> builtins.bool: ...
    def collect_files(self, project_root: builtins.str | os.PathLike | pathlib.Path) -> builtins.list[pathlib.Path]: ...
    def analyze(self, project_root: builtins.str | os.PathLike | pathlib.Path, files: typing.Optional[typing.Sequence[builtins.str | os.PathLike | pathlib.Path]] = None, *, strict: builtins.bool = ...) -> Graph:
        r"""
        Разбирает проект и возвращает граф.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class GoResolver:
    def __new__(cls) -> GoResolver: ...
    def prepare(self, project_root: builtins.str | os.PathLike | pathlib.Path, files: typing.Optional[typing.Sequence[builtins.str | os.PathLike | pathlib.Path]] = None) -> None:
        r"""
        Загружает и типизирует пакеты проекта.
        
        Список файлов не нужен: `go/packages` сам разбирает `go.mod` и
        подтягивает зависимости.
        """
    def resolve_all(self, queries: typing.Sequence[tuple[builtins.str | os.PathLike | pathlib.Path, builtins.int, builtins.int]]) -> builtins.list[typing.Optional[ResolvedRef]]: ...
    def definition_at(self, file: builtins.str | os.PathLike | pathlib.Path, line: builtins.int, col: builtins.int) -> typing.Optional[ResolvedRef]: ...
    def status(self) -> ResolverStatus: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class Graph:
    @property
    def nodes(self) -> builtins.dict[builtins.str, Node]: ...
    @property
    def relations(self) -> builtins.list[Relation]: ...
    @property
    def metadata(self) -> dict: ...
    def __new__(cls) -> Graph: ...
    def add_node(self, node: Node) -> None:
        r"""
        Добавляет узел; DuplicateNodeError при совпадении ID.
        """
    def add_relation(self, relation: Relation) -> None:
        r"""
        Добавляет ребро и сбрасывает индексы.
        """
    def merge(self, other: Graph, *, allow_shared: builtins.bool = ...) -> None:
        r"""
        Вливает другой граф.
        
        `allow_shared=True` разрешает совпадение *идентичных* узлов — так
        объединяются межъязыковые графы, где адаптеры разных языков намеренно
        порождают один и тот же BOUNDARY-узел. Коллизия двух *разных* узлов
        остаётся ошибкой и в этом режиме.
        """
    def to_dict(self) -> dict:
        r"""
        Сериализует граф в JSON-совместимый словарь.
        """
    def to_json(self, *, indent: typing.Optional[builtins.int] = None) -> builtins.str:
        r"""
        Сериализует граф в строку JSON.
        """
    @staticmethod
    def from_dict(data: dict) -> Graph:
        r"""
        Восстанавливает граф из вывода `to_dict`.
        """
    @staticmethod
    def from_json(text: builtins.str) -> Graph:
        r"""
        Восстанавливает граф из вывода `to_json`.
        """
    def diff(self, other: Graph) -> GraphDiff:
        r"""
        Структурный diff от этого графа (старого) к `other`.
        """
    def outgoing(self, node_id: builtins.str, kind: typing.Optional[RelationKind] = None) -> builtins.list[Relation]:
        r"""
        Рёбра, исходящие из `node_id`.
        """
    def incoming(self, node_id: builtins.str, kind: typing.Optional[RelationKind] = None) -> builtins.list[Relation]:
        r"""
        Рёбра, входящие в `node_id`.
        """
    def callees(self, node_id: builtins.str) -> builtins.list[Node]:
        r"""
        Кого вызывает `node_id`.
        """
    def callers(self, node_id: builtins.str) -> builtins.list[Node]:
        r"""
        Кто вызывает `node_id`.
        """
    def references_to(self, node_id: builtins.str) -> builtins.list[Node]:
        r"""
        Кто ссылается на `node_id`.
        """
    def neighbors(self, node_id: builtins.str, depth: builtins.int = ...) -> builtins.list[Node]:
        r"""
        Различные узлы в пределах `depth` переходов в любую сторону.
        """
    def nodes_by_kind(self, kind: NodeKind) -> builtins.list[Node]:
        r"""
        Все узлы данного вида.
        """
    def nodes_in_file(self, file_path: builtins.str) -> builtins.list[Node]:
        r"""
        Все узлы, объявленные в файле.
        """
    def nodes_by_name(self, name: builtins.str) -> builtins.list[Node]:
        r"""
        Узлы, у которых короткое или полное имя равно `name`.
        """
    def subgraph(self, node_ids: typing.Sequence[builtins.str]) -> Graph:
        r"""
        Новый граф из этих узлов и всех инцидентных им рёбер.
        """
    def subgraph_for_file(self, file_path: builtins.str) -> Graph:
        r"""
        Подграф из всех узлов файла и их рёбер.
        """
    def __len__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class GraphDiff:
    @property
    def added_nodes(self) -> builtins.list[Node]: ...
    @property
    def removed_nodes(self) -> builtins.list[Node]: ...
    @property
    def changed_nodes(self) -> builtins.list[tuple[Node, Node]]: ...
    @property
    def added_relations(self) -> builtins.list[Relation]: ...
    @property
    def removed_relations(self) -> builtins.list[Relation]: ...
    @property
    def is_empty(self) -> builtins.bool:
        r"""
        True, когда графы структурно идентичны.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class ImportClassifier:
    r"""
    Определяет происхождение импорта по заранее посчитанным наборам имён.
    
    Значения (ложатся в `Node.metadata["origin"]`): `stdlib`, `internal`,
    `third_party`, `unknown` — последнее означает «ни в одном наборе»
    (транзитивная зависимость или её отсутствие).
    """
    def __new__(cls, stdlib: typing.Optional[builtins.set[builtins.str]] = None, third_party: typing.Optional[builtins.set[builtins.str]] = None, internal: typing.Optional[builtins.set[builtins.str]] = None) -> ImportClassifier: ...
    def classify(self, top_level: builtins.str) -> builtins.str:
        r"""
        Происхождение по имени модуля верхнего уровня.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Node:
    @property
    def id(self) -> builtins.str: ...
    @property
    def kind(self) -> NodeKind: ...
    @property
    def qualified_name(self) -> builtins.str: ...
    @property
    def name(self) -> builtins.str: ...
    @property
    def file_path(self) -> typing.Optional[builtins.str]: ...
    @property
    def span(self) -> typing.Optional[Span]: ...
    @property
    def metadata(self) -> dict: ...
    def __new__(cls, id: builtins.str, kind: NodeKind, qualified_name: builtins.str, name: builtins.str, file_path: typing.Optional[builtins.str] = None, span: typing.Optional[Span] = None, metadata: typing.Optional[dict] = None) -> Node: ...
    def __repr__(self) -> builtins.str: ...
    def __eq__(self, other: Node) -> builtins.bool: ...

@typing.final
class OccurrenceRef:
    r"""
    Место использования, которое резолвер потом привяжет к определению.
    
    Координаты 1-based. Роли:
    `call` — место вызова функции/метода; `read` — чтение идентификатора;
    `write` — цель присваивания; `annotation` — аннотация типа или правая
    часть TypeAlias; `base` — базовый класс в списке наследования.
    """
    @property
    def role(self) -> builtins.str: ...
    @property
    def line(self) -> builtins.int: ...
    @property
    def col(self) -> builtins.int: ...
    @property
    def enclosing_id(self) -> builtins.str: ...
    @property
    def span(self) -> Span: ...
    def __new__(cls, role: builtins.str, line: builtins.int, col: builtins.int, enclosing_id: builtins.str, span: Span) -> OccurrenceRef: ...
    def __repr__(self) -> builtins.str: ...

class ParseError(CallixError):
    r"""
    Не удалось разобрать исходник.
    """
    ...

@typing.final
class PythonAdapter:
    r"""
    Языковой адаптер для Python-проектов.
    
    `analyze()` идёт тремя фазами: структура по каждому корню, затем один
    резолв на весь вызов, затем границы. Порядок не косметический —
    см. комментарии внутри.
    """
    def __new__(cls, dep_parsers: typing.Optional[typing.Any] = None, resolver: typing.Optional[typing.Any] = None, *, resolve: builtins.bool = ...) -> PythonAdapter:
        r"""
        Args:
        dep_parsers: свои парсеры манифестов (объекты с `can_parse` и
            `parse`). По умолчанию — встроенные: pyproject.toml,
            requirements*.txt, setup.cfg.
        resolver: свой резолвер символов (объект с `resolve_all`).
            По умолчанию — встроенный ty.
        resolve: False отключает резолв-фазу — граф останется
            структурным, а `resolver_status` в метаданных станет
            `unavailable`.
        """
    def language(self) -> builtins.str: ...
    def file_extensions(self) -> builtins.set[builtins.str]: ...
    def can_handle(self, project_root: builtins.str | os.PathLike | pathlib.Path) -> builtins.bool: ...
    def collect_files(self, project_root: builtins.str | os.PathLike | pathlib.Path) -> builtins.list[pathlib.Path]:
        r"""
        Все исходники под корнем, кроме служебных каталогов.
        """
    def analyze(self, project_root: builtins.str | os.PathLike | pathlib.Path, files: typing.Optional[typing.Sequence[builtins.str | os.PathLike | pathlib.Path]] = None, *, strict: builtins.bool = ...) -> Graph:
        r"""
        Разбирает проект и возвращает граф.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Relation:
    @property
    def source_id(self) -> builtins.str: ...
    @property
    def target_id(self) -> builtins.str: ...
    @property
    def kind(self) -> RelationKind: ...
    @property
    def metadata(self) -> dict: ...
    def __new__(cls, source_id: builtins.str, target_id: builtins.str, kind: RelationKind, metadata: typing.Optional[dict] = None) -> Relation: ...
    def __repr__(self) -> builtins.str: ...
    def __eq__(self, other: Relation) -> builtins.bool: ...

@typing.final
class ResolvedRef:
    r"""
    Символ, привязанный резолвером к своему определению. Координаты 1-based.
    """
    @property
    def full_name(self) -> builtins.str: ...
    @property
    def file_path(self) -> typing.Optional[builtins.str]: ...
    @property
    def line(self) -> builtins.int: ...
    @property
    def col(self) -> builtins.int: ...
    @property
    def kind(self) -> builtins.str: ...
    @property
    def origin(self) -> builtins.str: ...
    def __new__(cls, full_name: builtins.str, file_path: typing.Optional[builtins.str], line: builtins.int, col: builtins.int, kind: builtins.str, origin: builtins.str) -> ResolvedRef: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class ResolverMetrics:
    @property
    def queries(self) -> builtins.int:
        r"""
        Позиций отдано резолверу — по одной на место использования.
        """
    @queries.setter
    def queries(self, value: builtins.int) -> None:
        r"""
        Позиций отдано резолверу — по одной на место использования.
        """
    @property
    def resolved(self) -> builtins.int:
        r"""
        Запросов, вернувших определение.
        """
    @resolved.setter
    def resolved(self, value: builtins.int) -> None:
        r"""
        Запросов, вернувших определение.
        """
    @property
    def internal(self) -> builtins.int:
        r"""
        Определений, привязанных к узлу в графе.
        """
    @internal.setter
    def internal(self, value: builtins.int) -> None:
        r"""
        Определений, привязанных к узлу в графе.
        """
    @property
    def external(self) -> builtins.int:
        r"""
        Определений, ушедших в EXTERNAL_SYMBOL.
        """
    @external.setter
    def external(self, value: builtins.int) -> None:
        r"""
        Определений, ушедших в EXTERNAL_SYMBOL.
        """
    @property
    def unresolved(self) -> builtins.int:
        r"""
        Запросов, не давших ничего.
        """
    @unresolved.setter
    def unresolved(self, value: builtins.int) -> None:
        r"""
        Запросов, не давших ничего.
        """
    @property
    def seconds(self) -> builtins.float:
        r"""
        Секунд внутри `resolve_all`.
        """
    @seconds.setter
    def seconds(self, value: builtins.float) -> None:
        r"""
        Секунд внутри `resolve_all`.
        """
    @property
    def resolved_pct(self) -> builtins.float:
        r"""
        Доля запросов, вернувших определение, в процентах.
        """
    def __new__(cls, queries: builtins.int = ..., resolved: builtins.int = ..., internal: builtins.int = ..., external: builtins.int = ..., unresolved: builtins.int = ..., seconds: builtins.float = ...) -> ResolverMetrics: ...
    def merge(self, other: ResolverMetrics) -> None:
        r"""
        Складывает счётчики другого прохода в этот.
        """
    def as_dict(self) -> dict:
        r"""
        Плоский словарь для хранения в `graph.metadata`.
        """
    def __repr__(self) -> builtins.str: ...

class ResolverTimeout(ParseError):
    r"""
    Резолвер не уложился в таймаут.
    """
    ...

@typing.final
class RustAdapter:
    r"""
    Языковой адаптер для Rust-крейтов.
    """
    def __new__(cls, *, resolve: builtins.bool = ...) -> RustAdapter:
        r"""
        Args:
        resolve: False отключает резолв-фазу — граф останется
            структурным, а `resolver_status` станет `unavailable`.
        """
    def language(self) -> builtins.str: ...
    def file_extensions(self) -> builtins.set[builtins.str]: ...
    def can_handle(self, project_root: builtins.str | os.PathLike | pathlib.Path) -> builtins.bool: ...
    def collect_files(self, project_root: builtins.str | os.PathLike | pathlib.Path) -> builtins.list[pathlib.Path]: ...
    def analyze(self, project_root: builtins.str | os.PathLike | pathlib.Path, files: typing.Optional[typing.Sequence[builtins.str | os.PathLike | pathlib.Path]] = None, *, strict: builtins.bool = ...) -> Graph:
        r"""
        Разбирает воркспейс и возвращает граф.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class RustResolver:
    def __new__(cls) -> RustResolver: ...
    def prepare(self, project_root: builtins.str | os.PathLike | pathlib.Path, files: typing.Optional[typing.Sequence[builtins.str | os.PathLike | pathlib.Path]] = None) -> None:
        r"""
        Строит индекс SCIP для воркспейса.
        
        Список файлов не нужен: `rust-analyzer` сам разбирает `Cargo.toml` и
        индексирует весь воркспейс.
        """
    def resolve_all(self, queries: typing.Sequence[tuple[builtins.str | os.PathLike | pathlib.Path, builtins.int, builtins.int]]) -> builtins.list[typing.Optional[ResolvedRef]]: ...
    def definition_at(self, file: builtins.str | os.PathLike | pathlib.Path, line: builtins.int, col: builtins.int) -> typing.Optional[ResolvedRef]: ...
    def status(self) -> ResolverStatus: ...
    def __repr__(self) -> builtins.str: ...

class SerializationError(CallixError):
    r"""
    Ошибка (де)сериализации графа.
    """
    ...

@typing.final
class Span:
    @property
    def start_line(self) -> builtins.int: ...
    @property
    def start_col(self) -> builtins.int: ...
    @property
    def end_line(self) -> builtins.int: ...
    @property
    def end_col(self) -> builtins.int: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, start_line: builtins.int, start_col: builtins.int, end_line: builtins.int, end_col: builtins.int) -> Span: ...
    def contains(self, line: builtins.int, col: builtins.int) -> builtins.bool:
        r"""
        Содержит ли диапазон позицию (1-based).
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class SpanIndex:
    def __new__(cls) -> SpanIndex: ...
    def add_full(self, file_path: builtins.str, node_id: builtins.str, span: Span) -> None:
        r"""
        Регистрирует полный экстент узла.
        """
    def add_name(self, file_path: builtins.str, node_id: builtins.str, name_span: Span) -> None:
        r"""
        Регистрирует спан имени (идентификатора) узла.
        """
    @staticmethod
    def from_graph(graph: Graph) -> SpanIndex:
        r"""
        Собирает индекс по всем узлам графа, у которых есть спан.
        """
    def enclosing(self, file_path: builtins.str, line: builtins.int, col: builtins.int) -> typing.Optional[builtins.str]:
        r"""
        Внутренний узел, чей полный экстент содержит позицию (1-based).
        """
    def at(self, file_path: builtins.str, line: builtins.int, col: builtins.int) -> typing.Optional[builtins.str]:
        r"""
        Узел, чей спан имени содержит позицию (1-based).
        """

@typing.final
class TsImportClassifier:
    r"""
    Определяет происхождение импорта по заранее посчитанным наборам имён.
    
    В отличие от Python, ключом служит имя пакета, выведенное из спецификатора:
    `@scope/pkg/sub` → `@scope/pkg`, `lodash/fp` → `lodash`.
    """
    def __new__(cls, stdlib: typing.Optional[builtins.set[builtins.str]] = None, third_party: typing.Optional[builtins.set[builtins.str]] = None, internal: typing.Optional[builtins.set[builtins.str]] = None) -> TsImportClassifier: ...
    def classify(self, import_path: builtins.str) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class TsResolver:
    def __new__(cls) -> TsResolver: ...
    def prepare(self, project_root: builtins.str | os.PathLike | pathlib.Path, files: typing.Optional[typing.Sequence[builtins.str | os.PathLike | pathlib.Path]] = None) -> None:
        r"""
        Поднимает проект: typescript-go сам находит tsconfig.json и строит
        программу, поэтому список файлов ему не передаётся.
        """
    def resolve_all(self, queries: typing.Sequence[tuple[builtins.str | os.PathLike | pathlib.Path, builtins.int, builtins.int]]) -> builtins.list[typing.Optional[ResolvedRef]]:
        r"""
        Батч позиций → определения, порядок сохраняется.
        """
    def definition_at(self, file: builtins.str | os.PathLike | pathlib.Path, line: builtins.int, col: builtins.int) -> typing.Optional[ResolvedRef]:
        r"""
        Одна позиция → определение.
        """
    def status(self) -> ResolverStatus: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class TypeScriptAdapter:
    r"""
    Языковой адаптер для TypeScript-проектов.
    """
    def __new__(cls, *, resolve: builtins.bool = ...) -> TypeScriptAdapter:
        r"""
        Args:
        resolve: False отключает резолв-фазу — граф останется
            структурным, а `resolver_status` станет `unavailable`.
        """
    def language(self) -> builtins.str: ...
    def file_extensions(self) -> builtins.set[builtins.str]: ...
    def can_handle(self, project_root: builtins.str | os.PathLike | pathlib.Path) -> builtins.bool: ...
    def collect_files(self, project_root: builtins.str | os.PathLike | pathlib.Path) -> builtins.list[pathlib.Path]:
        r"""
        Исходники под корнем, кроме файлов деклараций.
        """
    def analyze(self, project_root: builtins.str | os.PathLike | pathlib.Path, files: typing.Optional[typing.Sequence[builtins.str | os.PathLike | pathlib.Path]] = None, *, strict: builtins.bool = ...) -> Graph:
        r"""
        Разбирает проект и возвращает граф.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class NodeKind(enum.Enum):
    PROJECT = ...
    MODULE = ...
    FILE = ...
    CLASS = ...
    FUNCTION = ...
    METHOD = ...
    PARAMETER = ...
    IMPORT = ...
    DEPENDENCY = ...
    EXTERNAL_SYMBOL = ...
    VARIABLE = ...
    ATTRIBUTE = ...
    TYPE_ALIAS = ...
    BOUNDARY = ...

    @property
    def value(self) -> builtins.str:
        r"""
        Строковое значение — то же, что у `enum.Enum` в graphlens.
        """
    @staticmethod
    def from_value(value: builtins.str) -> NodeKind:
        r"""
        Разбор из строкового значения; ValueError на неизвестном.
        """
    def __str__(self) -> builtins.str: ...

@typing.final
class RelationKind(enum.Enum):
    CONTAINS = ...
    DECLARES = ...
    IMPORTS = ...
    CALLS = ...
    REFERENCES = ...
    DEPENDS_ON = ...
    RESOLVES_TO = ...
    INHERITS_FROM = ...
    HAS_TYPE = ...
    EXPOSES = ...
    CONSUMES = ...
    COMMUNICATES_WITH = ...

    @property
    def value(self) -> builtins.str: ...
    @staticmethod
    def from_value(value: builtins.str) -> RelationKind: ...
    def __str__(self) -> builtins.str: ...

@typing.final
class ResolverStatus(enum.Enum):
    OK = ...
    DEGRADED = ...
    UNAVAILABLE = ...

    @property
    def value(self) -> builtins.str: ...
    @staticmethod
    def combine(statuses: typing.Sequence[ResolverStatus]) -> ResolverStatus:
        r"""
        Худший статус из переданных; пустой список — OK.
        """
    @staticmethod
    def from_value(value: typing.Any, default: typing.Optional[ResolverStatus] = None) -> ResolverStatus:
        r"""
        Терпимый разбор: нераспознанное значение даёт `default`
        (по умолчанию UNAVAILABLE), а не ValueError — чужой или
        поправленный руками граф не должен ронять чтение.
        """
    def __str__(self) -> builtins.str: ...

def apply_boundaries(graph: Graph, files: typing.Sequence[tuple[builtins.str, builtins.str, typing.Sequence[BoundaryRef]]]) -> None:
    r"""
    Фаза 3: узлы BOUNDARY и рёбра EXPOSES / CONSUMES.
    
    ID границы выводится только из `mechanism` + `key`, поэтому сервер на
    одном языке и клиент на другом дают один и тот же узел и склеиваются
    при слиянии графов.
    """

def apply_resolutions(graph: Graph, project_name: builtins.str, project_root: builtins.str | os.PathLike | pathlib.Path, span_index: SpanIndex, occurrences: typing.Sequence[tuple[builtins.str, OccurrenceRef]], refs: typing.Sequence[typing.Optional[ResolvedRef]]) -> ResolverMetrics:
    r"""
    Фаза 2: превращает ответы резолвера в рёбра.
    
    На каждое место использования: внутреннее определение ищется в
    `SpanIndex`, всё остальное падает в EXTERNAL_SYMBOL — так ребро не
    пропадает, даже когда цель вне графа.
    """

def build_root_structure(graph: Graph, project_root: builtins.str, py_root: builtins.str, files: typing.Sequence[builtins.str], stdlib: builtins.set[builtins.str], third_party: builtins.set[builtins.str]) -> tuple[builtins.str, builtins.list[tuple[builtins.str, OccurrenceRef]], builtins.list[tuple[builtins.str, builtins.str, builtins.list[BoundaryRef]]]]:
    r"""
    Фаза 1: структура и импорты одного корня Python-проекта.
    
    Возвращает `(project_name, [(абсолютный путь, место использования)])`.
    Резолв и извлечение границ идут позже и на уровне всего проекта, чтобы
    один резолвер и полный `SpanIndex` обслуживали все корни сразу.
    """

def classify_go_import(import_path: builtins.str, module_path: typing.Optional[builtins.str] = None, required: typing.Optional[builtins.set[builtins.str]] = None) -> builtins.str:
    r"""
    Классификация пути импорта Go.
    """

def classify_rust_import(import_path: builtins.str, crate_name: typing.Optional[builtins.str] = None, deps: typing.Optional[builtins.set[builtins.str]] = None) -> builtins.str:
    r"""
    Классификация пути `use` — точка входа для проверок.
    """

def collect_python_files(project_root: builtins.str) -> builtins.list[builtins.str]:
    r"""
    Все Python-файлы под корнем.
    """

def collect_typescript_files_py(project_root: builtins.str | os.PathLike | pathlib.Path) -> builtins.list[pathlib.Path]:
    r"""
    Все TypeScript-файлы под корнем, кроме деклараций.
    """

def detect_project_name(project_root: builtins.str) -> builtins.str: ...

def diff_graphs(old: Graph, new: Graph) -> GraphDiff:
    r"""
    Структурный diff от `old` к `new`. Порядок внутри каждого списка
    детерминирован: узлы отсортированы по ID, рёбра — по своему ключу.
    """

def ensure_schema_version(data: dict) -> None:
    r"""
    Падает с SerializationError на неподдерживаемой версии схемы.
    """

def extract_go_boundaries(source: bytes) -> builtins.list[BoundaryRef]:
    r"""
    Границы в одном исходнике — точка входа для проверок.
    """

def extract_python_boundaries(source: bytes) -> builtins.list[BoundaryRef]:
    r"""
    Границы в одном исходнике — точка входа для проверок и внешних вызовов.
    """

def extract_rust_boundaries(source: bytes) -> builtins.list[BoundaryRef]:
    r"""
    Границы в одном исходнике — точка входа для проверок.
    """

def extract_typescript_boundaries(source: bytes, tsx: builtins.bool = ...) -> builtins.list[BoundaryRef]:
    r"""
    Границы в одном исходнике — точка входа для проверок.
    """

def file_to_qualified_name(file_path: builtins.str, source_root: builtins.str) -> builtins.str: ...

def filter_nested_files(files: typing.Sequence[builtins.str], current_root: builtins.str, project_roots: typing.Sequence[builtins.str]) -> builtins.list[builtins.str]:
    r"""
    Отбрасывает файлы вложенных корней (родитель не разбирает подпроекты).
    """

def find_go_roots(root: builtins.str | os.PathLike | pathlib.Path) -> builtins.list[pathlib.Path]: ...

def find_python_roots(search_root: builtins.str) -> builtins.list[builtins.str]:
    r"""
    Корни Python-проектов внутри `search_root` (по одному на подпроект).
    """

def find_rust_roots(root: builtins.str | os.PathLike | pathlib.Path) -> builtins.list[pathlib.Path]: ...

def find_source_roots(project_root: builtins.str, files: typing.Sequence[builtins.str]) -> builtins.list[builtins.str]: ...

def find_typescript_roots(search_root: builtins.str | os.PathLike | pathlib.Path) -> builtins.list[pathlib.Path]: ...

def get_stdlib_names() -> builtins.set[builtins.str]: ...

def go_detect_project_name(root: builtins.str | os.PathLike | pathlib.Path) -> builtins.str: ...

def go_parse_dependencies(root: builtins.str | os.PathLike | pathlib.Path) -> builtins.set[builtins.str]: ...

def go_read_module_path(root: builtins.str | os.PathLike | pathlib.Path) -> typing.Optional[builtins.str]: ...

def is_go_project(root: builtins.str | os.PathLike | pathlib.Path) -> builtins.bool: ...

def is_package_init(file_path: builtins.str) -> builtins.bool:
    r"""
    `__init__.py` или `__init__.pyi`.
    """

def is_python_project(project_root: builtins.str) -> builtins.bool:
    r"""
    Есть ли под корнем Python: сначала маркеры, потом — любой `.py`.
    
    Откат по `.py` нужен для многоязычных монорепозиториев, где в корне
    нет Python-маркеров, но есть Python-подпакеты рядом с JS/Rust.
    """

def is_rust_project(root: builtins.str | os.PathLike | pathlib.Path) -> builtins.bool: ...

def is_typescript_project(project_root: builtins.str | os.PathLike | pathlib.Path) -> builtins.bool: ...

def make_boundary_id(mechanism: builtins.str, key: builtins.str) -> builtins.str:
    r"""
    Стабильный ID границы — не зависит ни от языка, ни от проекта, поэтому
    сервер на одном языке и клиент на другом дают один и тот же узел.
    """

def make_node_id(project_name: builtins.str, qualified_name: builtins.str, kind: builtins.str) -> builtins.str:
    r"""
    Стабильный ID узла: sha256("{project}::{kind}::{qualified_name}")[:16].
    """

def node_from_dict(data: dict) -> Node:
    r"""
    Обратное к [`node_to_dict`].
    """

def node_to_dict(node: Node) -> dict:
    r"""
    Сериализует узел в JSON-совместимый словарь.
    """

def normalize_http_path(raw: builtins.str) -> builtins.str:
    r"""
    Приводит маршрут или URL к ключу, не зависящему от хоста и параметров.
    
    Убирает схему и хост, query и фрагмент; схлопывает параметры пути всех
    стилей и конкретные числовые id (`/users/1` встречается с `/users/{}`);
    снимает завершающий слэш, кроме корня.
    """

def normalize_pkg_name(name: builtins.str) -> builtins.str:
    r"""
    Приводит имя дистрибутива к виду, сравнимому с именем импорта.
    
    Отрезает версии и extras (`requests>=2.0 [security]` → `requests`),
    переводит в нижний регистр, дефисы меняет на подчёркивания.
    Scoped-имена npm (`@scope/pkg`) остаются как есть.
    """

def parse_dependencies(project_root: builtins.str) -> builtins.set[builtins.str]:
    r"""
    Имена сторонних пакетов, объявленных в манифестах корня.
    """

def relation_from_dict(data: dict) -> Relation:
    r"""
    Обратное к [`relation_to_dict`].
    """

def relation_to_dict(relation: Relation) -> dict:
    r"""
    Сериализует ребро в JSON-совместимый словарь.
    """

def resolve_relative_import(current_module_qname: builtins.str, level: builtins.int, module: typing.Optional[builtins.str] = None) -> builtins.str:
    r"""
    Приводит относительный импорт к абсолютному имени.
    
    `level` — число ведущих точек (1 — текущий пакет, 2 — родительский).
    Пакет текущего модуля — это все части имени, кроме последней.
    """

def rust_detect_project_name(root: builtins.str | os.PathLike | pathlib.Path) -> builtins.str: ...

def rust_parse_dependencies(root: builtins.str | os.PathLike | pathlib.Path) -> builtins.set[builtins.str]: ...

def rust_read_crate_name(root: builtins.str | os.PathLike | pathlib.Path) -> typing.Optional[builtins.str]: ...

def ts_build_root_structure(graph: Graph, project_root: builtins.str | os.PathLike | pathlib.Path, lang_root: builtins.str | os.PathLike | pathlib.Path, files: typing.Sequence[builtins.str | os.PathLike | pathlib.Path]) -> tuple[builtins.str, builtins.list[tuple[builtins.str, OccurrenceRef]], builtins.list[tuple[builtins.str, builtins.str, builtins.list[BoundaryRef]]]]:
    r"""
    Структурная фаза одного корня — точка входа для проверок.
    """

def ts_detect_project_name(project_root: builtins.str | os.PathLike | pathlib.Path) -> builtins.str: ...

def ts_file_to_qualified_name(file_path: builtins.str | os.PathLike | pathlib.Path, source_root: builtins.str | os.PathLike | pathlib.Path) -> builtins.str: ...

def ts_find_source_roots(project_root: builtins.str | os.PathLike | pathlib.Path, files: typing.Sequence[builtins.str | os.PathLike | pathlib.Path]) -> builtins.list[pathlib.Path]: ...

def ts_get_stdlib_names() -> builtins.set[builtins.str]: ...

def ts_load_path_aliases(project_root: builtins.str | os.PathLike | pathlib.Path) -> builtins.dict[builtins.str, builtins.str]: ...

def ts_parse_dependencies(project_root: builtins.str | os.PathLike | pathlib.Path) -> builtins.set[builtins.str]: ...

def ts_resolve_relative_import(current_module_qname: builtins.str, import_path: builtins.str) -> builtins.str: ...

def visit_python_file(graph: Graph, project_name: builtins.str, file_path: builtins.str, module_qualified_name: builtins.str, file_node_id: builtins.str, source: bytes, classifier: typing.Optional[ImportClassifier] = None) -> builtins.list[OccurrenceRef]:
    r"""
    Разбирает один файл и наполняет граф его структурой.
    
    Рёбра CALLS/REFERENCES/HAS_TYPE/INHERITS_FROM здесь не создаются —
    вместо них возвращается список мест использования, который резолв-фаза
    на стороне Python привяжет к определениям.
    """

def visit_typescript_file(graph: Graph, project_name: builtins.str, file_path: builtins.str, module_qualified_name: builtins.str, file_node_id: builtins.str, source: bytes, source_root_name: builtins.str, classifier: typing.Optional[TsImportClassifier] = None, modules: typing.Optional[typing.Mapping[builtins.str, builtins.str]] = None, path_aliases: typing.Optional[typing.Mapping[builtins.str, builtins.str]] = None, tsx: builtins.bool = ...) -> builtins.list[OccurrenceRef]:
    r"""
    Разбирает один TypeScript-файл и наполняет граф его структурой.
    """


__version__: builtins.str
SCHEMA_VERSION: builtins.int
RESOLVER_STATUS_KEY: builtins.str
RESOLVER_METRICS_KEY: builtins.str
