# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
import os
import pathlib
import typing
__all__ = [
    "AdapterError",
    "BoundaryRef",
    "CallixError",
    "DuplicateNodeError",
    "EmbeddedTyResolver",
    "GoAdapter",
    "GoResolver",
    "Graph",
    "GraphDiff",
    "ImportClassifier",
    "Node",
    "NodeKind",
    "OccurrenceRef",
    "ParseError",
    "PythonAdapter",
    "Relation",
    "RelationKind",
    "ResolvedRef",
    "ResolverMetrics",
    "ResolverStatus",
    "ResolverTimeout",
    "RustAdapter",
    "RustResolver",
    "SerializationError",
    "Span",
    "SpanIndex",
    "TsImportClassifier",
    "TsResolver",
    "TypeScriptAdapter",
    "apply_boundaries",
    "apply_resolutions",
    "build_root_structure",
    "classify_go_import",
    "classify_rust_import",
    "collect_python_files",
    "collect_typescript_files_py",
    "detect_project_name",
    "diff_graphs",
    "ensure_schema_version",
    "extract_go_boundaries",
    "extract_python_boundaries",
    "extract_rust_boundaries",
    "extract_typescript_boundaries",
    "file_to_qualified_name",
    "filter_nested_files",
    "find_go_roots",
    "find_python_roots",
    "find_rust_roots",
    "find_source_roots",
    "find_typescript_roots",
    "get_stdlib_names",
    "go_detect_project_name",
    "go_parse_dependencies",
    "go_read_module_path",
    "is_go_project",
    "is_package_init",
    "is_python_project",
    "is_rust_project",
    "is_typescript_project",
    "make_boundary_id",
    "make_node_id",
    "node_from_dict",
    "node_to_dict",
    "normalize_http_path",
    "normalize_pkg_name",
    "parse_dependencies",
    "relation_from_dict",
    "relation_to_dict",
    "resolve_relative_import",
    "rust_detect_project_name",
    "rust_parse_dependencies",
    "rust_read_crate_name",
    "ts_build_root_structure",
    "ts_detect_project_name",
    "ts_file_to_qualified_name",
    "ts_find_source_roots",
    "ts_get_stdlib_names",
    "ts_load_path_aliases",
    "ts_parse_dependencies",
    "ts_resolve_relative_import",
    "visit_python_file",
    "visit_typescript_file",
]

class AdapterError(CallixError):
    r"""
    Error raised while the adapter was running.
    """
    ...

@typing.final
class BoundaryRef:
    r"""
    A single *port* on a cross-language boundary, found in the source.
    
    A boundary is a contract between services that no compiler resolves: an
    HTTP route, a gRPC method, a queue topic, a Temporal activity. Each side
    of the contract (the server `exposes`, the client `consumes`) is a port.
    
    Coordinates are 1-based and point at the port's site (a route decorator,
    a `fetch` call, a `publish` call) so the adapter can match it to the
    enclosing declaration.
    """
    @property
    def mechanism(self) -> builtins.str:
        r"""
        The boundary family: `http` | `grpc` | `queue` | `temporal`.
        """
    @property
    def role(self) -> builtins.str:
        r"""
        `server` (provides the contract) or `client` (consumes it).
        """
    @property
    def key(self) -> builtins.str:
        r"""
        The normalized matching key, for example `GET /users/{}`.
        """
    @property
    def line(self) -> builtins.int: ...
    @property
    def col(self) -> builtins.int: ...
    @property
    def confidence(self) -> builtins.float:
        r"""
        The extractor's confidence: 1.0 for a literal, less when inferred
        from context.
        """
    @property
    def detail(self) -> builtins.dict[builtins.str, builtins.str]:
        r"""
        Human-readable context: method, path, topic, framework.
        """
    def __new__(cls, mechanism: builtins.str, role: builtins.str, key: builtins.str, line: builtins.int, col: builtins.int, confidence: builtins.float = ..., detail: typing.Optional[typing.Mapping[builtins.str, builtins.str]] = None) -> BoundaryRef: ...
    def __repr__(self) -> builtins.str: ...

class CallixError(builtins.Exception):
    r"""
    Base callix error.
    """
    ...

class DuplicateNodeError(CallixError):
    r"""
    A node with this ID is already in the graph.
    """
    ...

@typing.final
class EmbeddedTyResolver:
    def __new__(cls, base_prefix: builtins.str) -> EmbeddedTyResolver: ...
    def prepare(self, project_root: builtins.str, files: typing.Optional[typing.Sequence[builtins.str]] = None) -> None:
        r"""
        Brings up ty's database for the project. `files` is unused: ty walks
        the project itself according to its own configuration — unlike the LSP
        version, which had to open files one at a time.
        """
    def resolve_all(self, queries: typing.Sequence[tuple[builtins.str, builtins.int, builtins.int]]) -> builtins.list[typing.Optional[ResolvedRef]]:
        r"""
        A batch of positions → definitions, order preserved.
        """
    def definition_at(self, file: builtins.str, line: builtins.int, col: builtins.int) -> typing.Optional[ResolvedRef]:
        r"""
        One position → a definition.
        """
    def status(self) -> ResolverStatus: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class GoAdapter:
    r"""
    The language adapter for Go projects.
    """
    def __new__(cls, *, resolve: builtins.bool = ...) -> GoAdapter:
        r"""
        Args:
        resolve: False turns the resolution phase off — the graph stays
            structural and `resolver_status` becomes `unavailable`.
        """
    def language(self) -> builtins.str: ...
    def file_extensions(self) -> builtins.set[builtins.str]: ...
    def can_handle(self, project_root: builtins.str | os.PathLike | pathlib.Path) -> builtins.bool: ...
    def collect_files(self, project_root: builtins.str | os.PathLike | pathlib.Path) -> builtins.list[pathlib.Path]: ...
    def analyze(self, project_root: builtins.str | os.PathLike | pathlib.Path, files: typing.Optional[typing.Sequence[builtins.str | os.PathLike | pathlib.Path]] = None, *, strict: builtins.bool = ...) -> Graph:
        r"""
        Analyses the project and returns the graph.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class GoResolver:
    def __new__(cls) -> GoResolver: ...
    def prepare(self, project_root: builtins.str | os.PathLike | pathlib.Path, files: typing.Optional[typing.Sequence[builtins.str | os.PathLike | pathlib.Path]] = None) -> None:
        r"""
        Loads and type-checks the project's packages.
        
        No file list is needed: `go/packages` parses `go.mod` and pulls in the
        dependencies itself.
        """
    def resolve_all(self, queries: typing.Sequence[tuple[builtins.str | os.PathLike | pathlib.Path, builtins.int, builtins.int]]) -> builtins.list[typing.Optional[ResolvedRef]]: ...
    def definition_at(self, file: builtins.str | os.PathLike | pathlib.Path, line: builtins.int, col: builtins.int) -> typing.Optional[ResolvedRef]: ...
    def status(self) -> ResolverStatus: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class Graph:
    @property
    def nodes(self) -> builtins.dict[builtins.str, Node]: ...
    @property
    def relations(self) -> builtins.list[Relation]: ...
    @property
    def metadata(self) -> dict: ...
    def __new__(cls) -> Graph: ...
    def add_node(self, node: Node) -> None:
        r"""
        Adds a node; raises DuplicateNodeError on an ID collision.
        """
    def add_relation(self, relation: Relation) -> None:
        r"""
        Adds an edge and invalidates the indices.
        """
    def merge(self, other: Graph, *, allow_shared: builtins.bool = ...) -> None:
        r"""
        Merges another graph in.
        
        `allow_shared=True` permits *identical* nodes to coincide — that is
        how cross-language graphs are combined, where adapters for different
        languages deliberately produce the same BOUNDARY node. A collision
        between two *different* nodes stays an error even in this mode.
        """
    def to_dict(self) -> dict:
        r"""
        Serializes the graph into a JSON-compatible dict.
        """
    def to_json(self, *, indent: typing.Optional[builtins.int] = None) -> builtins.str:
        r"""
        Serializes the graph into a JSON string.
        """
    @staticmethod
    def from_dict(data: dict) -> Graph:
        r"""
        Rebuilds a graph from `to_dict` output.
        """
    @staticmethod
    def from_json(text: builtins.str) -> Graph:
        r"""
        Rebuilds a graph from `to_json` output.
        """
    def diff(self, other: Graph) -> GraphDiff:
        r"""
        The structural diff from this graph (the old one) to `other`.
        """
    def outgoing(self, node_id: builtins.str, kind: typing.Optional[RelationKind] = None) -> builtins.list[Relation]:
        r"""
        Edges leaving `node_id`.
        """
    def incoming(self, node_id: builtins.str, kind: typing.Optional[RelationKind] = None) -> builtins.list[Relation]:
        r"""
        Edges entering `node_id`.
        """
    def callees(self, node_id: builtins.str) -> builtins.list[Node]:
        r"""
        What `node_id` calls.
        """
    def callers(self, node_id: builtins.str) -> builtins.list[Node]:
        r"""
        What calls `node_id`.
        """
    def references_to(self, node_id: builtins.str) -> builtins.list[Node]:
        r"""
        What references `node_id`.
        """
    def neighbors(self, node_id: builtins.str, depth: builtins.int = ...) -> builtins.list[Node]:
        r"""
        Distinct nodes within `depth` hops in either direction.
        """
    def nodes_by_kind(self, kind: NodeKind) -> builtins.list[Node]:
        r"""
        Every node of the given kind.
        """
    def nodes_in_file(self, file_path: builtins.str) -> builtins.list[Node]:
        r"""
        Every node declared in the file.
        """
    def nodes_by_name(self, name: builtins.str) -> builtins.list[Node]:
        r"""
        Nodes whose short or qualified name equals `name`.
        """
    def subgraph(self, node_ids: typing.Sequence[builtins.str]) -> Graph:
        r"""
        A new graph from these nodes and every edge incident to them.
        """
    def subgraph_for_file(self, file_path: builtins.str) -> Graph:
        r"""
        The subgraph of every node in the file, plus their edges.
        """
    def __len__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class GraphDiff:
    @property
    def added_nodes(self) -> builtins.list[Node]: ...
    @property
    def removed_nodes(self) -> builtins.list[Node]: ...
    @property
    def changed_nodes(self) -> builtins.list[tuple[Node, Node]]: ...
    @property
    def added_relations(self) -> builtins.list[Relation]: ...
    @property
    def removed_relations(self) -> builtins.list[Relation]: ...
    @property
    def is_empty(self) -> builtins.bool:
        r"""
        True when the graphs are structurally identical.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class ImportClassifier:
    r"""
    Determines an import's origin from precomputed name sets.
    
    The values (stored in `Node.metadata["origin"]`): `stdlib`, `internal`,
    `third_party`, `unknown` — the last one meaning "in none of the sets"
    (a transitive dependency, or no dependency at all).
    """
    def __new__(cls, stdlib: typing.Optional[builtins.set[builtins.str]] = None, third_party: typing.Optional[builtins.set[builtins.str]] = None, internal: typing.Optional[builtins.set[builtins.str]] = None) -> ImportClassifier: ...
    def classify(self, top_level: builtins.str) -> builtins.str:
        r"""
        The origin for a top-level module name.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Node:
    @property
    def id(self) -> builtins.str: ...
    @property
    def kind(self) -> NodeKind: ...
    @property
    def qualified_name(self) -> builtins.str: ...
    @property
    def name(self) -> builtins.str: ...
    @property
    def file_path(self) -> typing.Optional[builtins.str]: ...
    @property
    def span(self) -> typing.Optional[Span]: ...
    @property
    def metadata(self) -> dict: ...
    def __new__(cls, id: builtins.str, kind: NodeKind, qualified_name: builtins.str, name: builtins.str, file_path: typing.Optional[builtins.str] = None, span: typing.Optional[Span] = None, metadata: typing.Optional[dict] = None) -> Node: ...
    def __repr__(self) -> builtins.str: ...
    def __eq__(self, other: Node) -> builtins.bool: ...

@typing.final
class OccurrenceRef:
    r"""
    A use-site the resolution pass will later bind to a definition.
    
    Coordinates are 1-based. Roles:
    `call` — a function/method call site; `read` — an identifier read;
    `write` — an assignment target; `annotation` — a type annotation or the
    right-hand side of a TypeAlias; `base` — a base class in an inheritance
    list.
    """
    @property
    def role(self) -> builtins.str: ...
    @property
    def line(self) -> builtins.int: ...
    @property
    def col(self) -> builtins.int: ...
    @property
    def enclosing_id(self) -> builtins.str: ...
    @property
    def span(self) -> Span: ...
    def __new__(cls, role: builtins.str, line: builtins.int, col: builtins.int, enclosing_id: builtins.str, span: Span) -> OccurrenceRef: ...
    def __repr__(self) -> builtins.str: ...

class ParseError(CallixError):
    r"""
    Could not parse the source.
    """
    ...

@typing.final
class PythonAdapter:
    r"""
    The language adapter for Python projects.
    
    `analyze()` runs in three phases: structure per root, then a single
    resolution pass for the whole call, then boundaries. The order is not
    cosmetic — see the comments inside.
    """
    def __new__(cls, dep_parsers: typing.Optional[typing.Any] = None, resolver: typing.Optional[typing.Any] = None, *, resolve: builtins.bool = ...) -> PythonAdapter:
        r"""
        Args:
        dep_parsers: custom manifest parsers (objects with `can_parse` and
            `parse`). Defaults to the built-in ones: pyproject.toml,
            requirements*.txt, setup.cfg.
        resolver: a custom symbol resolver (an object with `resolve_all`).
            Defaults to the embedded ty.
        resolve: False turns the resolution phase off — the graph stays
            structural and `resolver_status` in the metadata becomes
            `unavailable`.
        """
    def language(self) -> builtins.str: ...
    def file_extensions(self) -> builtins.set[builtins.str]: ...
    def can_handle(self, project_root: builtins.str | os.PathLike | pathlib.Path) -> builtins.bool: ...
    def collect_files(self, project_root: builtins.str | os.PathLike | pathlib.Path) -> builtins.list[pathlib.Path]:
        r"""
        Every source under the root, excluding service directories.
        """
    def analyze(self, project_root: builtins.str | os.PathLike | pathlib.Path, files: typing.Optional[typing.Sequence[builtins.str | os.PathLike | pathlib.Path]] = None, *, strict: builtins.bool = ...) -> Graph:
        r"""
        Analyses the project and returns the graph.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Relation:
    @property
    def source_id(self) -> builtins.str: ...
    @property
    def target_id(self) -> builtins.str: ...
    @property
    def kind(self) -> RelationKind: ...
    @property
    def metadata(self) -> dict: ...
    def __new__(cls, source_id: builtins.str, target_id: builtins.str, kind: RelationKind, metadata: typing.Optional[dict] = None) -> Relation: ...
    def __repr__(self) -> builtins.str: ...
    def __eq__(self, other: Relation) -> builtins.bool: ...

@typing.final
class ResolvedRef:
    r"""
    A symbol the resolver bound to its definition. Coordinates are 1-based.
    """
    @property
    def full_name(self) -> builtins.str: ...
    @property
    def file_path(self) -> typing.Optional[builtins.str]: ...
    @property
    def line(self) -> builtins.int: ...
    @property
    def col(self) -> builtins.int: ...
    @property
    def kind(self) -> builtins.str: ...
    @property
    def origin(self) -> builtins.str: ...
    def __new__(cls, full_name: builtins.str, file_path: typing.Optional[builtins.str], line: builtins.int, col: builtins.int, kind: builtins.str, origin: builtins.str) -> ResolvedRef: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class ResolverMetrics:
    @property
    def queries(self) -> builtins.int:
        r"""
        Positions handed to the resolver — one per use-site.
        """
    @queries.setter
    def queries(self, value: builtins.int) -> None:
        r"""
        Positions handed to the resolver — one per use-site.
        """
    @property
    def resolved(self) -> builtins.int:
        r"""
        Queries that returned a definition.
        """
    @resolved.setter
    def resolved(self, value: builtins.int) -> None:
        r"""
        Queries that returned a definition.
        """
    @property
    def internal(self) -> builtins.int:
        r"""
        Definitions bound to a node in the graph.
        """
    @internal.setter
    def internal(self, value: builtins.int) -> None:
        r"""
        Definitions bound to a node in the graph.
        """
    @property
    def external(self) -> builtins.int:
        r"""
        Definitions that fell through to an EXTERNAL_SYMBOL.
        """
    @external.setter
    def external(self, value: builtins.int) -> None:
        r"""
        Definitions that fell through to an EXTERNAL_SYMBOL.
        """
    @property
    def unresolved(self) -> builtins.int:
        r"""
        Queries that returned nothing.
        """
    @unresolved.setter
    def unresolved(self, value: builtins.int) -> None:
        r"""
        Queries that returned nothing.
        """
    @property
    def seconds(self) -> builtins.float:
        r"""
        Seconds spent inside `resolve_all`.
        """
    @seconds.setter
    def seconds(self, value: builtins.float) -> None:
        r"""
        Seconds spent inside `resolve_all`.
        """
    @property
    def resolved_pct(self) -> builtins.float:
        r"""
        Share of queries that returned a definition, in percent.
        """
    def __new__(cls, queries: builtins.int = ..., resolved: builtins.int = ..., internal: builtins.int = ..., external: builtins.int = ..., unresolved: builtins.int = ..., seconds: builtins.float = ...) -> ResolverMetrics: ...
    def merge(self, other: ResolverMetrics) -> None:
        r"""
        Folds another pass's counters into this one.
        """
    def as_dict(self) -> dict:
        r"""
        A flat dict for storage in `graph.metadata`.
        """
    def __repr__(self) -> builtins.str: ...

class ResolverTimeout(ParseError):
    r"""
    The resolver exceeded its timeout.
    """
    ...

@typing.final
class RustAdapter:
    r"""
    The language adapter for Rust crates.
    """
    def __new__(cls, *, resolve: builtins.bool = ...) -> RustAdapter:
        r"""
        Args:
        resolve: False turns the resolution phase off — the graph stays
            structural and `resolver_status` becomes `unavailable`.
        """
    def language(self) -> builtins.str: ...
    def file_extensions(self) -> builtins.set[builtins.str]: ...
    def can_handle(self, project_root: builtins.str | os.PathLike | pathlib.Path) -> builtins.bool: ...
    def collect_files(self, project_root: builtins.str | os.PathLike | pathlib.Path) -> builtins.list[pathlib.Path]: ...
    def analyze(self, project_root: builtins.str | os.PathLike | pathlib.Path, files: typing.Optional[typing.Sequence[builtins.str | os.PathLike | pathlib.Path]] = None, *, strict: builtins.bool = ...) -> Graph:
        r"""
        Analyses the workspace and returns the graph.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class RustResolver:
    def __new__(cls) -> RustResolver: ...
    def prepare(self, project_root: builtins.str | os.PathLike | pathlib.Path, files: typing.Optional[typing.Sequence[builtins.str | os.PathLike | pathlib.Path]] = None) -> None:
        r"""
        Builds the SCIP index for the workspace.
        
        No file list is needed: `rust-analyzer` parses `Cargo.toml` and indexes
        the whole workspace itself.
        """
    def resolve_all(self, queries: typing.Sequence[tuple[builtins.str | os.PathLike | pathlib.Path, builtins.int, builtins.int]]) -> builtins.list[typing.Optional[ResolvedRef]]: ...
    def definition_at(self, file: builtins.str | os.PathLike | pathlib.Path, line: builtins.int, col: builtins.int) -> typing.Optional[ResolvedRef]: ...
    def status(self) -> ResolverStatus: ...
    def __repr__(self) -> builtins.str: ...

class SerializationError(CallixError):
    r"""
    Graph (de)serialization error.
    """
    ...

@typing.final
class Span:
    @property
    def start_line(self) -> builtins.int: ...
    @property
    def start_col(self) -> builtins.int: ...
    @property
    def end_line(self) -> builtins.int: ...
    @property
    def end_col(self) -> builtins.int: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, start_line: builtins.int, start_col: builtins.int, end_line: builtins.int, end_col: builtins.int) -> Span: ...
    def contains(self, line: builtins.int, col: builtins.int) -> builtins.bool:
        r"""
        Whether the range contains the (1-based) position.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class SpanIndex:
    def __new__(cls) -> SpanIndex: ...
    def add_full(self, file_path: builtins.str, node_id: builtins.str, span: Span) -> None:
        r"""
        Registers a node's full extent.
        """
    def add_name(self, file_path: builtins.str, node_id: builtins.str, name_span: Span) -> None:
        r"""
        Registers a node's name (identifier) span.
        """
    @staticmethod
    def from_graph(graph: Graph) -> SpanIndex:
        r"""
        Builds the index over every graph node that carries a span.
        """
    def enclosing(self, file_path: builtins.str, line: builtins.int, col: builtins.int) -> typing.Optional[builtins.str]:
        r"""
        The innermost node whose full extent contains the (1-based) position.
        """
    def at(self, file_path: builtins.str, line: builtins.int, col: builtins.int) -> typing.Optional[builtins.str]:
        r"""
        The node whose name span contains the (1-based) position.
        """

@typing.final
class TsImportClassifier:
    r"""
    Determines an import's origin from precomputed name sets.
    
    Unlike Python, the key is the package name derived from the specifier:
    `@scope/pkg/sub` → `@scope/pkg`, `lodash/fp` → `lodash`.
    """
    def __new__(cls, stdlib: typing.Optional[builtins.set[builtins.str]] = None, third_party: typing.Optional[builtins.set[builtins.str]] = None, internal: typing.Optional[builtins.set[builtins.str]] = None) -> TsImportClassifier: ...
    def classify(self, import_path: builtins.str) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class TsResolver:
    def __new__(cls) -> TsResolver: ...
    def prepare(self, project_root: builtins.str | os.PathLike | pathlib.Path, files: typing.Optional[typing.Sequence[builtins.str | os.PathLike | pathlib.Path]] = None) -> None:
        r"""
        Brings the project up: typescript-go finds tsconfig.json and builds
        the program itself, so no file list is passed to it.
        """
    def resolve_all(self, queries: typing.Sequence[tuple[builtins.str | os.PathLike | pathlib.Path, builtins.int, builtins.int]]) -> builtins.list[typing.Optional[ResolvedRef]]:
        r"""
        A batch of positions → definitions, order preserved.
        """
    def definition_at(self, file: builtins.str | os.PathLike | pathlib.Path, line: builtins.int, col: builtins.int) -> typing.Optional[ResolvedRef]:
        r"""
        One position → a definition.
        """
    def status(self) -> ResolverStatus: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class TypeScriptAdapter:
    r"""
    The language adapter for TypeScript projects.
    """
    def __new__(cls, *, resolve: builtins.bool = ...) -> TypeScriptAdapter:
        r"""
        Args:
        resolve: False turns the resolution phase off — the graph stays
            structural and `resolver_status` becomes `unavailable`.
        """
    def language(self) -> builtins.str: ...
    def file_extensions(self) -> builtins.set[builtins.str]: ...
    def can_handle(self, project_root: builtins.str | os.PathLike | pathlib.Path) -> builtins.bool: ...
    def collect_files(self, project_root: builtins.str | os.PathLike | pathlib.Path) -> builtins.list[pathlib.Path]:
        r"""
        Sources under the root, declaration files excluded.
        """
    def analyze(self, project_root: builtins.str | os.PathLike | pathlib.Path, files: typing.Optional[typing.Sequence[builtins.str | os.PathLike | pathlib.Path]] = None, *, strict: builtins.bool = ...) -> Graph:
        r"""
        Analyses the project and returns the graph.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class NodeKind(enum.Enum):
    PROJECT = ...
    MODULE = ...
    FILE = ...
    CLASS = ...
    FUNCTION = ...
    METHOD = ...
    PARAMETER = ...
    IMPORT = ...
    DEPENDENCY = ...
    EXTERNAL_SYMBOL = ...
    VARIABLE = ...
    ATTRIBUTE = ...
    TYPE_ALIAS = ...
    BOUNDARY = ...

    @property
    def value(self) -> builtins.str:
        r"""
        The string value — the same one `enum.Enum` carries in graphlens.
        """
    @staticmethod
    def from_value(value: builtins.str) -> NodeKind:
        r"""
        Parses from a string value; raises ValueError on an unknown one.
        """
    def __str__(self) -> builtins.str: ...

@typing.final
class RelationKind(enum.Enum):
    CONTAINS = ...
    DECLARES = ...
    IMPORTS = ...
    CALLS = ...
    REFERENCES = ...
    DEPENDS_ON = ...
    RESOLVES_TO = ...
    INHERITS_FROM = ...
    HAS_TYPE = ...
    EXPOSES = ...
    CONSUMES = ...
    COMMUNICATES_WITH = ...

    @property
    def value(self) -> builtins.str: ...
    @staticmethod
    def from_value(value: builtins.str) -> RelationKind: ...
    def __str__(self) -> builtins.str: ...

@typing.final
class ResolverStatus(enum.Enum):
    OK = ...
    DEGRADED = ...
    UNAVAILABLE = ...

    @property
    def value(self) -> builtins.str: ...
    @staticmethod
    def combine(statuses: typing.Sequence[ResolverStatus]) -> ResolverStatus:
        r"""
        The worst of the given statuses; an empty list is OK.
        """
    @staticmethod
    def from_value(value: typing.Any, default: typing.Optional[ResolverStatus] = None) -> ResolverStatus:
        r"""
        Lenient parsing: an unrecognized value yields `default`
        (UNAVAILABLE unless stated otherwise) rather than a ValueError — a
        foreign or hand-edited graph must not break reading.
        """
    def __str__(self) -> builtins.str: ...

def apply_boundaries(graph: Graph, files: typing.Sequence[tuple[builtins.str, builtins.str, typing.Sequence[BoundaryRef]]]) -> None:
    r"""
    Phase 3: BOUNDARY nodes and EXPOSES / CONSUMES edges.
    
    A boundary's ID derives from `mechanism` + `key` alone, so a server in one
    language and a client in another produce the same node and join up when
    graphs are merged.
    """

def apply_resolutions(graph: Graph, project_name: builtins.str, project_root: builtins.str | os.PathLike | pathlib.Path, span_index: SpanIndex, occurrences: typing.Sequence[tuple[builtins.str, OccurrenceRef]], refs: typing.Sequence[typing.Optional[ResolvedRef]]) -> ResolverMetrics:
    r"""
    Phase 2: turns resolver answers into edges.
    
    Per use-site: an internal definition is looked up in the `SpanIndex`,
    everything else falls through to an EXTERNAL_SYMBOL — so the edge is never
    lost, even when the target lies outside the graph.
    """

def build_root_structure(graph: Graph, project_root: builtins.str, py_root: builtins.str, files: typing.Sequence[builtins.str], stdlib: builtins.set[builtins.str], third_party: builtins.set[builtins.str]) -> tuple[builtins.str, builtins.list[tuple[builtins.str, OccurrenceRef]], builtins.list[tuple[builtins.str, builtins.str, builtins.list[BoundaryRef]]]]:
    r"""
    Phase 1: structure and imports for one Python project root.
    
    Returns `(project_name, [(absolute path, use-site)])`. Resolution and
    boundary extraction happen later at project level, so that a single
    resolver and a full `SpanIndex` serve every root at once.
    """

def classify_go_import(import_path: builtins.str, module_path: typing.Optional[builtins.str] = None, required: typing.Optional[builtins.set[builtins.str]] = None) -> builtins.str:
    r"""
    Classification of a Go import path.
    """

def classify_rust_import(import_path: builtins.str, crate_name: typing.Optional[builtins.str] = None, deps: typing.Optional[builtins.set[builtins.str]] = None) -> builtins.str:
    r"""
    Classification of a `use` path — the entry point for checks.
    """

def collect_python_files(project_root: builtins.str) -> builtins.list[builtins.str]:
    r"""
    Every Python file under the root.
    """

def collect_typescript_files_py(project_root: builtins.str | os.PathLike | pathlib.Path) -> builtins.list[pathlib.Path]:
    r"""
    Every TypeScript file under the root, declarations excluded.
    """

def detect_project_name(project_root: builtins.str) -> builtins.str: ...

def diff_graphs(old: Graph, new: Graph) -> GraphDiff:
    r"""
    The structural diff from `old` to `new`. Ordering within each list is
    deterministic: nodes are sorted by ID, edges by their key.
    """

def ensure_schema_version(data: dict) -> None:
    r"""
    Fails with SerializationError on an unsupported schema version.
    """

def extract_go_boundaries(source: bytes) -> builtins.list[BoundaryRef]:
    r"""
    Boundaries in a single source — the entry point for checks.
    """

def extract_python_boundaries(source: bytes) -> builtins.list[BoundaryRef]:
    r"""
    Boundaries in a single source — the entry point for checks and external
    callers.
    """

def extract_rust_boundaries(source: bytes) -> builtins.list[BoundaryRef]:
    r"""
    Boundaries in a single source — the entry point for checks.
    """

def extract_typescript_boundaries(source: bytes, tsx: builtins.bool = ...) -> builtins.list[BoundaryRef]:
    r"""
    Boundaries in a single source — the entry point for checks.
    """

def file_to_qualified_name(file_path: builtins.str, source_root: builtins.str) -> builtins.str: ...

def filter_nested_files(files: typing.Sequence[builtins.str], current_root: builtins.str, project_roots: typing.Sequence[builtins.str]) -> builtins.list[builtins.str]:
    r"""
    Drops nested roots' files (a parent does not parse its subprojects).
    """

def find_go_roots(root: builtins.str | os.PathLike | pathlib.Path) -> builtins.list[pathlib.Path]: ...

def find_python_roots(search_root: builtins.str) -> builtins.list[builtins.str]:
    r"""
    Python project roots inside `search_root` (one per subproject).
    """

def find_rust_roots(root: builtins.str | os.PathLike | pathlib.Path) -> builtins.list[pathlib.Path]: ...

def find_source_roots(project_root: builtins.str, files: typing.Sequence[builtins.str]) -> builtins.list[builtins.str]: ...

def find_typescript_roots(search_root: builtins.str | os.PathLike | pathlib.Path) -> builtins.list[pathlib.Path]: ...

def get_stdlib_names() -> builtins.set[builtins.str]: ...

def go_detect_project_name(root: builtins.str | os.PathLike | pathlib.Path) -> builtins.str: ...

def go_parse_dependencies(root: builtins.str | os.PathLike | pathlib.Path) -> builtins.set[builtins.str]: ...

def go_read_module_path(root: builtins.str | os.PathLike | pathlib.Path) -> typing.Optional[builtins.str]: ...

def is_go_project(root: builtins.str | os.PathLike | pathlib.Path) -> builtins.bool: ...

def is_package_init(file_path: builtins.str) -> builtins.bool:
    r"""
    `__init__.py` or `__init__.pyi`.
    """

def is_python_project(project_root: builtins.str) -> builtins.bool:
    r"""
    Whether there is Python under the root: markers first, then any `.py`.
    
    The `.py` fallback exists for polyglot monorepos whose root carries no
    Python markers but holds Python subpackages next to JS/Rust.
    """

def is_rust_project(root: builtins.str | os.PathLike | pathlib.Path) -> builtins.bool: ...

def is_typescript_project(project_root: builtins.str | os.PathLike | pathlib.Path) -> builtins.bool: ...

def make_boundary_id(mechanism: builtins.str, key: builtins.str) -> builtins.str:
    r"""
    Stable boundary ID — independent of both language and project, so a
    server in one language and a client in another produce the same node.
    """

def make_node_id(project_name: builtins.str, qualified_name: builtins.str, kind: builtins.str) -> builtins.str:
    r"""
    Stable node ID: sha256("{project}::{kind}::{qualified_name}")[:16].
    """

def node_from_dict(data: dict) -> Node:
    r"""
    The inverse of [`node_to_dict`].
    """

def node_to_dict(node: Node) -> dict:
    r"""
    Serializes a node into a JSON-compatible dict.
    """

def normalize_http_path(raw: builtins.str) -> builtins.str:
    r"""
    Reduces a route or URL to a key independent of host and parameters.
    
    Strips scheme and host, query and fragment; collapses path parameters of
    every style along with concrete numeric ids (`/users/1` has to meet
    `/users/{}`); drops the trailing slash except at the root.
    """

def normalize_pkg_name(name: builtins.str) -> builtins.str:
    r"""
    Normalizes a distribution name into a form comparable with an import
    name.
    
    Strips versions and extras (`requests>=2.0 [security]` → `requests`),
    lowercases, and turns hyphens into underscores. Scoped npm names
    (`@scope/pkg`) are left as they are.
    """

def parse_dependencies(project_root: builtins.str) -> builtins.set[builtins.str]:
    r"""
    Third-party package names declared in the root's manifests.
    """

def relation_from_dict(data: dict) -> Relation:
    r"""
    The inverse of [`relation_to_dict`].
    """

def relation_to_dict(relation: Relation) -> dict:
    r"""
    Serializes an edge into a JSON-compatible dict.
    """

def resolve_relative_import(current_module_qname: builtins.str, level: builtins.int, module: typing.Optional[builtins.str] = None) -> builtins.str:
    r"""
    Resolves a relative import to an absolute name.
    
    `level` is the number of leading dots (1 for the current package, 2 for
    the parent). The current module's package is every part of its name but
    the last.
    """

def rust_detect_project_name(root: builtins.str | os.PathLike | pathlib.Path) -> builtins.str: ...

def rust_parse_dependencies(root: builtins.str | os.PathLike | pathlib.Path) -> builtins.set[builtins.str]: ...

def rust_read_crate_name(root: builtins.str | os.PathLike | pathlib.Path) -> typing.Optional[builtins.str]: ...

def ts_build_root_structure(graph: Graph, project_root: builtins.str | os.PathLike | pathlib.Path, lang_root: builtins.str | os.PathLike | pathlib.Path, files: typing.Sequence[builtins.str | os.PathLike | pathlib.Path]) -> tuple[builtins.str, builtins.list[tuple[builtins.str, OccurrenceRef]], builtins.list[tuple[builtins.str, builtins.str, builtins.list[BoundaryRef]]]]:
    r"""
    One root's structural phase — the entry point for checks.
    """

def ts_detect_project_name(project_root: builtins.str | os.PathLike | pathlib.Path) -> builtins.str: ...

def ts_file_to_qualified_name(file_path: builtins.str | os.PathLike | pathlib.Path, source_root: builtins.str | os.PathLike | pathlib.Path) -> builtins.str: ...

def ts_find_source_roots(project_root: builtins.str | os.PathLike | pathlib.Path, files: typing.Sequence[builtins.str | os.PathLike | pathlib.Path]) -> builtins.list[pathlib.Path]: ...

def ts_get_stdlib_names() -> builtins.set[builtins.str]: ...

def ts_load_path_aliases(project_root: builtins.str | os.PathLike | pathlib.Path) -> builtins.dict[builtins.str, builtins.str]: ...

def ts_parse_dependencies(project_root: builtins.str | os.PathLike | pathlib.Path) -> builtins.set[builtins.str]: ...

def ts_resolve_relative_import(current_module_qname: builtins.str, import_path: builtins.str) -> builtins.str: ...

def visit_python_file(graph: Graph, project_name: builtins.str, file_path: builtins.str, module_qualified_name: builtins.str, file_node_id: builtins.str, source: bytes, classifier: typing.Optional[ImportClassifier] = None) -> builtins.list[OccurrenceRef]:
    r"""
    Parses one file and fills the graph with its structure.
    
    CALLS/REFERENCES/HAS_TYPE/INHERITS_FROM edges are not created here —
    instead a list of use-sites is returned, which the resolution pass on the
    Python side binds to definitions.
    """

def visit_typescript_file(graph: Graph, project_name: builtins.str, file_path: builtins.str, module_qualified_name: builtins.str, file_node_id: builtins.str, source: bytes, source_root_name: builtins.str, classifier: typing.Optional[TsImportClassifier] = None, modules: typing.Optional[typing.Mapping[builtins.str, builtins.str]] = None, path_aliases: typing.Optional[typing.Mapping[builtins.str, builtins.str]] = None, tsx: builtins.bool = ...) -> builtins.list[OccurrenceRef]:
    r"""
    Parses one TypeScript file and fills the graph with its structure.
    """


__version__: builtins.str
SCHEMA_VERSION: builtins.int
RESOLVER_STATUS_KEY: builtins.str
RESOLVER_METRICS_KEY: builtins.str
